# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: kenichi1203
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: Dr_nishi_development

test:
  <<: *default
  database: Dr_nishi_test

production:
  <<: *default
  database: Dr_nishi_production
  username: root
  password: Kenichi@1203
  socket: /var/lib/mysql/mysql.sock